server:
  port: 9001
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    username: imran
    url: jdbc:postgresql://192.168.1.159:54320/department-db
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true

eureka:
  instance:
    hostname: 192.168.1.159
#    non-secure-port: 80
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.1.159:8761/eureka